package models.Types;

public enum Type {
    OGNISTY, WODNY, BSNIOWY, DUCHOWY, ELEKTRYCZNY, KAMIENNY, LATAJACY, LODOWY, MROCZNY, NORMALNY, PSYCHICZNY, ROBACZY, SMOCZY, STALOWY, TRAWIASTY, TRUJACY, WALCZACY, ZIEMNY
}
